### ISSUE TITLE
Не получается изменить размер окна

### ISSUE THREAD

**Issue by vsemozhetbyt** [nongeneric/lsd2dsl#1]
Windows 7 sp1, lsd2dsl-0.3.0. Открытое окно программы можно распахнуть на весь экран, но в обычном состоянии оно занимает всё пространство по вертикали и почти всё по горизонтали. При этом изменить размер нельзя ни в одном направлении, будто окно диалоговое. Может, есть какая-то опция для этого в QT? Во-первых, это сбивает с толку (поначалу вообще не ясно, всё ли окно помещается на экране по вертикали, а подвигать его нельзя вверх-вниз), во-вторых, не очень удобно, когда хочется следить за прогрессом и одновременно работать в каком-то другом окне.

**Comment by nongeneric** [comment]
Это у окна неудачно минимальный размер задан -- 1200х800. Не подумал про небольшие мониторы. Сменю на 500х250. Начальный размер тоже уменьшу.
![500x250](https://cloud.githubusercontent.com/assets/7548041/6098284/a83b6004-afea-11e4-8dc1-bbd013147c28.png)
Должно быть нормально.

**Comment by vsemozhetbyt** [comment]
Спасибо большое.
