### ISSUE TITLE
some issues in lsd2dsl-0.5.0

### ISSUE THREAD

**Issue by vsemozhetbyt** [nongeneric/lsd2dsl#12]
Sorry, not sure if the same issues present in the previous versions.

1. Source files get `.dsl.` added before their extensions: `dictionary.dsl.ann`, `dictionary.dsl.bmp`, `dictionary.dsl.dsl`.

2. If a dictionary has assets (images), they are extracted to the folder of the `lsd2dsl-qtgui.exe`, not to the selected folder for other source files.

Thank you for the great tool!

**Comment by nongeneric** [comment]
Well, that was embarrassing :)
Thank you for reporting. I uploaded a new release with the fix.

**Comment by vsemozhetbyt** [comment]
Thank you!
