### ISSUE TITLE
WAVs from unpacked LSA dictionary are defective

### ISSUE THREAD

**Issue by Kzer-Za** [nongeneric/lsd2dsl#13]
If I unpack this dictionary https://atakua.org/p/dict/apresyan-goldendict/Speech.lsa, the wav files are defective, they are played too quickly and with respectively higher pitch. The lsa file is correct, if I add it to GoldenDict, it plays the pronunciation normally.

(Если распаковать с помощью lsd2dsl вот этот словарь: https://atakua.org/p/dict/apresyan-goldendict/Speech.lsa, то wav-файлы выходят битые, они проигрываются слишком быстро и в высокой тональности. Исходный lsa-файл нормален, если добавить его к словарям в базе GoldenDict'а, то GoldenDict проигрывает произношения из этого словаря нормально).

**Comment by nongeneric** [comment]
Поправил. Не учитывался правильный sample rate. Я выложил под win обновленную сборку.

**Comment by nongeneric** [comment]
> Кстати, почему только win32?

Исторически сложилось) Когда-то в ~2012 году ради совместимости делал win32. Теперь уже совсем неактуально, но особо смысла менять нету.

**Comment by Kzer-Za** [comment]
Отлично! :) Давно собирался перепаковать этот словарь и объединить с еще одним.
