### ISSUE TITLE
problem with [trn] TAG

### ISSUE THREAD

**Issue by Aliaksandr3by** [nongeneric/lsd2dsl#16]
![image](https://user-images.githubusercontent.com/11432724/113016114-d4658400-9186-11eb-9169-2563d3fe7175.png)

**Comment by nongeneric** [comment]
Hi,
Can you send me the original lsd dictionary?

**Comment by Aliaksandr3by** [comment]
https://rutracker.org/forum/viewtopic.php?t=5264130

**Comment by nongeneric** [comment]
Looking at this entry in the decompiled DSL file I see the correct result:

```
ящерица
	[p][i][c][trn1][com]ж.[/com][/c][/i][/p]
	[m1][trn]lizard[/trn1][/trn][/m]
```

GoldenDict 1.5.0-RC2 also correctly parses it and ignores the **trn1** tag:

![image](https://user-images.githubusercontent.com/7548041/113224557-67401480-9294-11eb-9bd0-4aa4623164a5.png)

So it might be a problem with your version.

**Comment by Aliaksandr3by** [comment]
1.5.0-RC2-477-g9686906

![image](https://user-images.githubusercontent.com/11432724/113247445-b94c5e80-92c3-11eb-9bb7-9899c05a4b67.png)

**Comment by Aliaksandr3by** [comment]
might you test the dict ob your PC?
http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&start=1960

**Comment by nongeneric** [comment]
Yep, I have the same problem with 1.5.0-RC2-477-g9686906 that I took from the ru-board thread. I guess you need to ask goldendict devs about it or try another build.
