### ISSUE TITLE
Pronunciation characters are incorrect in LingvoUniversalEnRu.dsl from Lingvo 12

### ISSUE THREAD

**Issue by geniot** [nongeneric/lsd2dsl#17]
LingvoUniversalEnRu from x6:
`\[[t]'ærɪ[/t]\]`
Lingvo 12:
`\[[t]'‡ЇЎ[/t]\]`

It is probably related to encoding. I've checked the Python decompilation. Same problem.

**Comment by nongeneric** [comment]
It looks like Lingvo 12 uses a special bitmap font to display transcriptions and doesn't treat the text inside the [t] tag as Unicode. I guess it would be possible to create a mapping to Unicode and use it when converting older dictionaries. Though it's probably not worth it.

Are you aware of any non-system dictionaries that also have this problem?

**Comment by geniot** [comment]
>Are you aware of any non-system dictionaries that also have this problem?
Nope. And you are right - it's not worth it. Same dictionary from x6 looks much better in terms of content and transcription characters are ok.
