### ISSUE TITLE
Decompilation of PhraseBookRuEs.lsa failed with error can't open file ... ¿fuma?.wav

### ISSUE THREAD

**Issue by geniot** [nongeneric/lsd2dsl#19]
I know it has to do with the question mark character, is there any way I can work around this failure?

**Comment by nongeneric** [comment]
Currently only by using linux, sorry. I considered renaming files with offending characters, but didn't do that to preserve both the original names and consistency between windows and linux builds.

Also, if you simply want to use the dictionary, you don't usually need to unpack LSA files in the first place. They are natively supported by GoldenDict, for example.

**Comment by geniot** [comment]
I tried using wine with Windows executable. Same result on Linux file system.

~/Downloads/lsd2dsl-0.5.4-win64$ wine lsd2dsl.exe --lsa /home/vitaly/Downloads/PhraseBookRuEs.lsa
PhraseBookRuEs.lsa   1% [                                                  ]an error occured while processing dictionary: can't open file PhraseBookRuEs.extracted/┬┐fuma?.wav

I can't easily build the project on Linux (boost, sndfile, qt5 aren't easy to set up for me). I plan to use the lsa data in another dictionary server I'm writing in Java. So GoldenDict won't help me much, except maybe for reference.

**Comment by nongeneric** [comment]
Yeah, wine won't do. You need natively built binaries.

Just follow [the instructions](https://rcebits.com/lsd2dsl/building.html) if you have access to Fedora, or install similar packages if you are on another distro (like libsndfile-dev for Ubuntu, etc). The dependencies are pretty common and should be in the repos of most distributions.

**Comment by geniot** [comment]
Thanks a lot for this link. I've been trying to set up the libraries in CLion. But no luck.
Now with these instructions I could successfully build the project and decompile the lsa file on Ubuntu. At some point I had to remove -Werror from CMakeLists file. And then add -lpthread -lm to target_link_libraries as recommended here: 
https://stackoverflow.com/questions/25617839/undefined-reference-to-symbol-pthread-key-deleteglibc-2-2-5
But all's well that ends well.
Perhaps you could consider producing a zip archive with fastest store method. This would solve this filesystem problem.

**Comment by nongeneric** [comment]
Nice. I'm glad it worked out.
You are probably right about making a zip archive, I'll think about implementing it.
