### ISSUE TITLE
Replace Qt5WebKitWidgets

### ISSUE THREAD

**Issue by 1over137** [nongeneric/lsd2dsl#20]
I cannot compile this because I do not have this library installed. This module has been deprecated for a long time by now and is not available in many linux distributions. Could you any of the following:
- Replace it with Qt5WebEngine
- Provide statically linked linux builds
- Provide an option to not build the GUI
Thanks

**Comment by nongeneric** [comment]
WebKit is used to render tables for Duden dictionaries, that's why it's required for the console version too. I'll see what I can do.

**Comment by totoroot** [comment]
@nongeneric Any updates on this?

**Comment by nongeneric** [comment]
Sorry for the late reply @totoroot. I have a prototype that uses the new WebEngine instead of WebKit, but it needs a little more work.

**Comment by nongeneric** [comment]
The master now depends on Qt6 and WebEngine.
