### ISSUE TITLE
Unicode '--out' paths need proper handling

### ISSUE THREAD

**Issue by wildekat** [nongeneric/lsd2dsl#21]
Посмотрите, пожалуйста. Если хоть где-нибудь в пути к --out есть не-ascii, программа отказывается работать.
Похоже, для работы с этими путями используются non-unicode-aware функции:

![lsd2dsl](https://user-images.githubusercontent.com/1102981/200166165-aeaa7142-aa77-433e-a781-46b903aad7bb.png)

А, ещё надо опечатку исправить: occur**r**ed

**Comment by nongeneric** [comment]
Уф, с юникод-путями под windows всё было плохо. Исправил все случаи какие заметил, надеюсь ничего не упустил. Опубликовал новый релиз с исправлениями https://github.com/nongeneric/lsd2dsl/releases/tag/v0.5.5

Спасибо за репорт.

**Comment by wildekat** [comment]
Вам спасибо, всё заработало.

**Comment by wildekat** [comment]
@nongeneric
Где-то ещё сидит часть этого бага ("zip file" - это .dsl.files.zip):
![lsd2dsl-0 5 5](https://user-images.githubusercontent.com/1102981/225946053-eb582581-dc56-444e-a09b-71db3c1cf61d.png)

И при распаковке LSA искажаются non-ascii символы в именах wav-файлов (вы это когда-то починили, но теперь оно снова сломалось).

**Comment by nongeneric** [comment]
Каюсь, lsa поломал :) В последнем релизе должны обе проблемы быть исправлены.
