### ISSUE TITLE
café.wav from SoundEn.lsa (x6) exported as cafâÐ¹.wav

### ISSUE THREAD

**Issue by lexicograph** [nongeneric/lsd2dsl#22]
I think the encoding of file names can still be improved. I'm using Windows 10.
Same for "décor.wav", "outdoor café.wav", "thank you — youre welcome.wav"

**Comment by nongeneric** [comment]
I think in this case the lsa dictionary itself is at fault. The entry's name in sounden.lsa (that is suppossed to be utf16le) is \u0063\u0061\u0066\u251c\u0493\u002e\u0077\u0061\u0076 which can be decoded to some nonsense like "caf├ғ.wav". The same is true for other entries. The archive seems to contain both versions in each case, e.g.

```
name: decor.wav utf16: 0064 0065 0063 006f 0072 002e 0077 0061 0076
name: d├йcor.wav utf16: 0064 251c 0439 0063 006f 0072 002e 0077 0061 0076
```

Interestingly soundfr.lsa contains a properly encoded version of "décor.wav"

`name: décor.wav utf16: 0064 00e9 0063 006f 0072 002e 0077 0061 0076`

**Comment by nongeneric** [comment]
In addition to those cases, other file names were also incorrect, that should now be fixed in the latest release.
