### ISSUE TITLE
Decompilation aborts with «can't create zip file»

### ISSUE THREAD

**Issue by palashman** [nongeneric/lsd2dsl#23]
Здравствуйте!
Я декомпилировал системные словари из X6, и на некоторых из них программа вываливалась с ошибкой: «**can't create zip file**».
Все проблемные lsd-словари я залил в облако: https://disk.yandex.ru/d/32VeST-QcclfjQ .

**Comment by nongeneric** [comment]
Наверное windows и русские буквы в пути к output? Попробуйте использовать только латиницу в путях. Я все никак не добью до конца эти проблемы с юникодом в файловой системе :) Попробую исправить попозже.

**Comment by palashman** [comment]
Да, проблема оказалась в русских буквах в пути. На английских декомпиляция прошла успешна!
Благодарю -))

**Comment by nongeneric** [comment]
В последнем релизе проблема должна быть исправлена.

**Comment by palashman** [comment]
Спасибо, полёт нормальный! -)
