### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by GD-fix** [nongeneric/lsd2dsl#24]
When there will be binary releases for Linux (GNU, Android), OS from Apple an other?

Thanks in advance.

**Comment by nongeneric** [comment]
I don't see much benefit in non-windows binary releases. Linux would be easy enough with AppImage, but it's already pretty easy to compile from sources. I don't have access to or experience with macOS, so can't comment on that.

And I'm not sure that mobile releases would make sense (either source or binary). Do you have a specific use case in mind?

**Comment by GD-fix** [comment]
1. For example, on my GNU/Linux OS (previous year snapshot of OpenSUSE Tumbleweed, DVD full install) it didn't compile. Different GNU/Linux distributives from different companies are using different packets. So, the binaries compiled with statically linked libraries are solving this problem. I don't have access to or experience with MacOS or Windows too, but how I know, these OSes are proprietary and so are using the same packets from the only company each. Therefore I don't see much benefit in windows binary releases.
2. I don't using mobile devices, but how I know, lsd/dsl formats are widely using there ([for example](https://4pda.to/forum/index.php?showtopic=267685&st=7720)).
