### ISSUE TITLE
Error reading samples

### ISSUE THREAD

**Issue by light2yellow** [nongeneric/lsd2dsl#3]
Using `SoundEn.lsa` from ABBYY Lingvo x6 European Version 16.2.2.64 the error occurs. Convertation stops at 76%. Is it possible to do something?
![screenshot_20160622_182158](https://cloud.githubusercontent.com/assets/10786469/16274517/3c765e0a-38a6-11e6-938e-01d0d85f13aa.png)

**Comment by light2yellow** [comment]
You can download the file [here](https://mega.nz/#!EBYjCZgQ).

**Comment by nongeneric** [comment]
That's strange. I could not check the file, the link said I needed a decryption key. So I've tried a slightly different version
```
$ md5sum sounden.lsa 
b8d6dce7e7d962c2dcb6167b4de13b07  sounden.lsa
```
And it worked.

**Comment by light2yellow** [comment]
Sorry, I wanted to include the key but forgot to do this. [Here it is](https://mega.nz/#!EBYjCZgQ!AfeODFETW46Tu2wT_sXl5Z9XYlZVKoMQrXKrU9lA9fA).
```
$ md5sum SoundEn.lsa       
976e8762e87db29c61a2364dbd94d7ef  SoundEn.lsa
```
Yes, the files are different. Anyway, seems to be that my version is corrupted.

**Comment by nongeneric** [comment]
Nice, a single bit difference.
```
< 064ca200: 2fb9 d777 3b1b 1a67 e7b3 b89d e755 b461  /..w;..g.....U.a
---
> 064ca200: 2fb9 d777 331b 1a67 e7b3 b89d e755 b461  /..w3..g.....U.a
```

**Comment by light2yellow** [comment]
Is it possible to manually fix this?

**Comment by nongeneric** [comment]
Glad to hear that. You are welcome.
